#!/usr/bin/env python3
"""Freeze Group 8 design only after annual dependency, schema, categorical, value-binding and reference-resolution gates PASS."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
ENGINE_VERSION="0.8.0";SCHEMA_VERSION="8.0.0"
def canon(v:Any)->str:return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False)
def write(path:Path,v:dict[str,Any])->None:path.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument('--group8-root',type=Path,required=True);ap.add_argument('--annual-registry',type=Path,required=True);ap.add_argument('--adapter-map',type=Path,required=True);ap.add_argument('--categorical-dictionary',type=Path,required=True);ap.add_argument('--value-bindings',type=Path,required=True);ap.add_argument('--reference-resolution',type=Path,required=True);ap.add_argument('--source-semantics',type=Path,required=True);ap.add_argument('--group7-amendment',type=Path,required=True);a=ap.parse_args()
 root=a.group8_root.resolve();annual=json.loads(a.annual_registry.read_text());adapters=json.loads(a.adapter_map.read_text());cats=json.loads(a.categorical_dictionary.read_text());bindings=json.loads(a.value_bindings.read_text());resolution=json.loads(a.reference_resolution.read_text());srcsem=json.loads(a.source_semantics.read_text());g7=json.loads(a.group7_amendment.read_text())
 gates=[('annual',annual.get('status')=='PASS'),('adapter',adapters.get('status')=='PASS'),('categorical',cats.get('status')=='PASS'),('bindings',bindings.get('status')=='PASS'),('resolution',resolution.get('status')=='PASS'),('source_semantics',srcsem.get('status')=='PASS'),('g7',g7.get('status')=='PASS_RECOVERY_AMENDMENT')]
 bad=[n for n,ok in gates if not ok]
 if bad:raise RuntimeError(f'freeze gates failed: {bad}')
 if annual.get('group7_source_closure_commit_sha')!=g7.get('source_closure_commit_sha'):raise RuntimeError('Group7 closure identity mismatch')
 if bindings.get('categorical_dictionary_hash')!=cats.get('dictionary_hash'):raise RuntimeError('binding/category hash mismatch')
 if bindings.get('source_semantics_evidence_hash')!=srcsem.get('evidence_hash'):raise RuntimeError('binding/source-semantics hash mismatch')
 if resolution.get('binding_hash')!=bindings.get('binding_hash'):raise RuntimeError('reference-resolution/binding hash mismatch')
 cfg=json.loads((root/'FROZEN_CONFIG_DRAFT.json').read_text());cfg.update({'config_status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':srcsem['evidence_hash'],'design_reference_resolution_hash':resolution['resolution_hash'],'resolved_definition_references':resolution['resolved_references'],'group7_recovery_reference':{'mode':g7['recovery_reference_mode'],'anchor_tag':g7['recovery_release_anchor_tag'],'anchor_commit_sha':g7['recovery_release_anchor_commit_sha'],'logical_recovery_id':g7['logical_recovery_id']}});payload=copy.deepcopy(cfg);payload.pop('config_id',None);cfg['config_id']='cfg8_'+hashlib.sha256(canon(payload).encode()).hexdigest();write(root/'FROZEN_CONFIG.json',cfg)
 defs=json.loads((root/'01_DEFINITION_REGISTRY_CANDIDATE_v2.json').read_text());defs.update({'status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'config_id':cfg['config_id'],'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':srcsem['evidence_hash'],'reference_resolution_hash':resolution['resolution_hash']});defs['registry_hash']=hashlib.sha256(canon({k:v for k,v in defs.items() if k!='registry_hash'}).encode()).hexdigest();write(root/'01_DEFINITION_REGISTRY.json',defs)
 contract=json.loads((root/'contracts/UPSTREAM_INPUT_CONTRACT_DRAFT.json').read_text());contract.update({'contract_version':'1.0.0','status':'FROZEN','annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':srcsem['evidence_hash']});mapping={'group1_canonical_bars':'source','group2_regime':'group2','group3_structure':'group3','group4_zones':'group4','group5_liquidity':'group5','group6_imbalance_delivery':'group6','group7_blocks':'group7'}
 for key,item in contract.get('inputs',{}).items():
  group=mapping.get(key)
  if group:item['exact_table_adapter']={'adapter_map':'UPSTREAM_ADAPTER_MAP.json','group_key':group,'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary':'UPSTREAM_CATEGORICAL_DICTIONARY.json','categorical_dictionary_hash':cats['dictionary_hash'],'value_bindings':'UPSTREAM_VALUE_BINDINGS.json','value_binding_hash':bindings['binding_hash']}
 contract['contract_hash']=hashlib.sha256(canon({k:v for k,v in contract.items() if k!='contract_hash'}).encode()).hexdigest();write(root/'contracts/UPSTREAM_INPUT_CONTRACT.json',contract)
 schema=(root/'02_SCHEMA_DRAFT.sql').read_text();(root/'02_SCHEMA.sql').write_text(schema);schema_hash=hashlib.sha256(schema.encode()).hexdigest()
 design=(root/'00_DESIGN_LOCK_DRAFT.md').read_text();design=design.replace('## Design Lock Draft v0.8.0-draft.1','## Design Lock v0.8.0');design=design.replace('**Status:** DRAFT ONLY — NOT FROZEN — ENGINE BUILD AND ANNUAL EXECUTION FORBIDDEN UNTIL DEPENDENCY INTAKE PASS','**Status:** FROZEN — DEPENDENCY INTAKE PASS — ENGINE BUILD AUTHORIZED FOR 2023 ONLY; 2024 OOS EXECUTION FORBIDDEN UNTIL 2023 FREEZE');design=design.replace('**Data release tag:** `moebot-group7-v0.7.5`.','**Recovered annual data reference:** closure-anchored recovery assets on `moebot-group7-v0.7.5-closure`, governed by `Group_7/registry/DATA_RELEASE_RECOVERY_AMENDMENT_v1.json`.')
 start=design.find('## 3. Dependency and freeze gate');end=design.find('## 4. Time and causality contract')
 if start<0 or end<=start:raise RuntimeError('dependency gate section not found')
 gate=f'''## 3. Dependency and freeze gate\n\n**FROZEN PASS.**\n\n1. Group 7 source closure `{g7['source_closure_tag']}` resolves to `{g7['source_closure_commit_sha']}` and recovery amendment is `{g7['status']}`.\n2. Historical clobbered Group7 data tag is forbidden for new dependencies; closure-anchored recovery assets are SHA-pinned.\n3. Corrected Groups2–6 runtime bundle v3 restores with exact engine identities.\n4. Real annual Groups2–5 dependencies pass v2↔v3 stable-ID and semantic equivalence, additive publication, and public clean-room verification.\n5. Published canonical Group6 remains the frozen Group6 input; every explicit Group2–5 reference it carries resolves against corrected-v3 upstream IDs. Rerun-vs-published Group6 differences are retained as diagnostics, not silently normalized.\n6. Real 2023/2024 schemas for source and Groups2–7 are introspected and mandatory adapters are cross-year stable.\n7. Real consumed categorical values are captured for both years; source-code semantics are SHA-verified; frozen value bindings admit only verified meanings. Unknown values remain raw/unclassified.\n8. Definition Candidate v2 is the only registry eligible for freeze; all config aliases and value-binding references resolve explicitly.\n9. Annual registry hash `{annual['registry_hash']}`; adapter hash `{adapters['adapter_map_hash']}`; categorical hash `{cats['dictionary_hash']}`; binding hash `{bindings['binding_hash']}`; reference-resolution hash `{resolution['resolution_hash']}`; source-semantics hash `{srcsem['evidence_hash']}`.\n10. Guessed identifiers, mutable dependencies, future-return fields, ranking of schools/definitions, and look-ahead remain forbidden.\n\n''';design=design[:start]+gate+design[end:]
 design+=f'''\n## Frozen artifact identities\n\n- Engine version: `{ENGINE_VERSION}`\n- Schema version: `{SCHEMA_VERSION}`\n- Config ID: `{cfg['config_id']}`\n- Definition registry hash: `{defs['registry_hash']}`\n- Upstream contract hash: `{contract['contract_hash']}`\n- SQL schema SHA-256: `{schema_hash}`\n- Annual dependency registry hash: `{annual['registry_hash']}`\n- Adapter map hash: `{adapters['adapter_map_hash']}`\n- Categorical dictionary hash: `{cats['dictionary_hash']}`\n- Value binding hash: `{bindings['binding_hash']}`\n- Source semantics evidence hash: `{srcsem['evidence_hash']}`\n- Reference resolution hash: `{resolution['resolution_hash']}`\n''';(root/'00_DESIGN_LOCK.md').write_text(design)
 status=json.loads((root/'STATUS.json').read_text());status.update({'annual_execution_authorized':True,'config_id':cfg['config_id'],'design_frozen':True,'engine_build_authorized':True,'officially_closed':False,'proposed_engine_version':ENGINE_VERSION,'proposed_schema_version':SCHEMA_VERSION,'status':'DESIGN_FROZEN_ENGINE_BUILD_AUTHORIZED_2023_ONLY','required_group7_data_release_tag':None,'required_group7_recovery_anchor_tag':g7['recovery_release_anchor_tag'],'required_group7_recovery_anchor_commit_sha':g7['recovery_release_anchor_commit_sha'],'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':srcsem['evidence_hash'],'reference_resolution_hash':resolution['resolution_hash']});status['dependency_intake']={'verdict':'PASS','closure_reference':'PASS','group7_recovery_amendment':'PASS','annual_upstream_registry':'PASS','real_cross_year_adapter_map':'PASS','real_cross_year_categorical_dictionary':'PASS','source_verified_value_bindings':'PASS','design_reference_resolution':'PASS','runtime_bundle_v3':'PASS'};write(root/'STATUS.json',status)
 manifest={'format_version':2,'status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'config_id':cfg['config_id'],'definition_registry_hash':defs['registry_hash'],'upstream_contract_hash':contract['contract_hash'],'schema_sha256':schema_hash,'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':adapters['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':srcsem['evidence_hash'],'reference_resolution_hash':resolution['resolution_hash'],'group7_closure_tag':g7['source_closure_tag'],'group7_closure_commit_sha':g7['source_closure_commit_sha']};manifest['design_freeze_hash']=hashlib.sha256(canon(manifest).encode()).hexdigest();write(root/'DESIGN_FREEZE_MANIFEST.json',manifest);print(json.dumps(manifest,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
