#!/usr/bin/env python3
"""Fail-closed pre-official gate aggregation for canonical stage-4 execution."""
from __future__ import annotations
import argparse,json,subprocess
from pathlib import Path
from group8_context_rejection_fastpath import IndexedContextRejectionEngine,STAGE4_PARTITION_COUNT
from moebot_group8_engine_v0_8_0 import stable_hash

def head_sha()->str:return subprocess.run(['git','rev-parse','HEAD'],check=True,text=True,capture_output=True).stdout.strip()
def main()->int:
 p=argparse.ArgumentParser();p.add_argument('--artifacts-root',type=Path,required=True);p.add_argument('--workflow',type=Path,required=True);p.add_argument('--parity-report',type=Path,required=True);p.add_argument('--benchmark-dir',type=Path,required=True);p.add_argument('--report',type=Path,required=True);a=p.parse_args();head=head_sha();status=json.loads((a.artifacts_root/'STATUS.json').read_text());parity=json.loads(a.parity_report.read_text());plan=IndexedContextRejectionEngine.stage4_partition_plan();wf=a.workflow.read_text()
 parity_pass=parity.get('status')=='PASS' and parity.get('parity',{}).get('status')=='PASS' and parity.get('benchmark_role_parity',{}).get('status')=='PASS' and parity.get('benchmark_role_parity',{}).get('receipt_content_equal_before_publication') is True
 negatives=parity.get('negative_regressions',{});required={'missing_partition','repeated_partition','conflicting_receipt','modified_partition_output','wrong_plan_hash','wrong_execution_order','finalize_before_complete','idempotent_retry'};negative_pass=set(negatives)==required and all(v=='PASS' for v in negatives.values())
 reports=[json.loads(x.read_text()) for x in sorted(a.benchmark_dir.rglob('stage4-benchmark-*.json'))];indices=sorted(int(r['partition_index']) for r in reports);complete=indices==list(range(STAGE4_PARTITION_COUNT))
 identity=all(r.get('status')=='PASS' and r.get('mode')=='benchmark' and r.get('role')=='STAGE4_FULL_JOB_BENCHMARK_ONLY' and r.get('github_head_sha')==head and r.get('plan_hash')==plan['plan_hash'] and r.get('checkpoint_3_published') is False and r.get('official_receipt_published') is False and r.get('source_tag')!=r.get('output_tag') and str(r.get('output_tag','')).endswith(head[:12]) and r.get('free_only') is True and r.get('oos_2024_accessed') is False and r.get('runtime_safety_pass') is True for r in reports)
 worst=max((float(r['full_job_wall_seconds']) for r in reports),default=float('inf'));runtime=complete and identity and worst<=14400
 official_count=wf.count('--mode official');partition_chain=('stage4-p00:\n    needs: safety-decision' in wf and all(f'stage4-p{i:02d}:\n    needs: stage4-p{i-1:02d}' in wf for i in range(1,STAGE4_PARTITION_COUNT)));workflow_checks={'benchmark_mode_present':'--mode benchmark' in wf,'official_partition_count':official_count==24,'exact_head_checkout':'ref: "${{ github.event.pull_request.head.sha }}"' in wf,'stage4_finalizer_job':'stage4-finalize:\n    needs: stage4-p23' in wf,'partition_chain_guard':partition_chain,'oos_lock_guard':'annual_execution_2024_authorized' in wf,'free_runner':'ubuntu-latest' in wf,'obsolete_segmented_driver_absent':'python "$GROUP8_ROOT/code/group8_segmented_annual_core.py"' not in wf,'one_shot_stage4_absent':'--start 4 --end 4 --report' not in wf,'single_executable_finalizer':wf.count('python "$GROUP8_ROOT/code/group8_stage4_finalize_release.py"')==1,'stage5_after_finalizer':'stage-5:\n    needs: stage4-finalize' in wf,'stages_0_3_not_rerun':all(t not in wf for t in ('--start 0','--start 1','--start 2','--start 3')),'self_hosted_absent':'runs-on: self-hosted' not in wf};workflow_ok=all(workflow_checks.values())
 free=status['free_only_policy']['paid_runner_allowed'] is False and status['free_only_policy']['paid_service_allowed'] is False;lock=status['annual_execution_2024_authorized'] is False;ranges=[{'range_identity':f"{plan['plan_id']}:range-{i:02d}-{i:02d}",'first_partition':i,'last_partition':i} for i in range(STAGE4_PARTITION_COUNT)]
 gates={'PARITY_PASS':parity_pass,'NEGATIVE_REGRESSIONS_PASS':negative_pass,'FULL_DATA_BENCHMARK_PASS':complete and identity,'RUNTIME_SAFETY_PASS':runtime,'WORKFLOW_YAML_VALIDATION_PASS':workflow_ok,'FREE_ONLY_PASS':free,'2024_LOCK_CONFIRMED':lock};payload={'status':'PASS' if all(gates.values()) else 'FAIL','github_head_sha':head,'gates':gates,'workflow_checks':workflow_checks,'worst_full_job_wall_seconds':worst,'safety_limit_seconds':14400,'selected_partition_count':STAGE4_PARTITION_COUNT,'frozen_job_ranges':ranges,'plan_id':plan['plan_id'],'plan_hash':plan['plan_hash'],'benchmark_report_count':len(reports),'benchmark_only_contract_verified':identity,'official_execution_authorized':all(gates.values()),'oos_2024_accessed':False,'free_only':True};payload['report_hash']=stable_hash(payload);a.report.parent.mkdir(parents=True,exist_ok=True);a.report.write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');print(json.dumps(payload,indent=2,sort_keys=True))
 if payload['status']!='PASS':raise RuntimeError(f'pre-official gate failure:{gates}; workflow_checks:{workflow_checks}')
 return 0
if __name__=='__main__':raise SystemExit(main())
