#!/usr/bin/env python3
"""Freeze Group8 v0.8.0 only after coherent corrected-v3 dependency gates PASS."""
from __future__ import annotations
import argparse,copy,hashlib,json
from pathlib import Path
from typing import Any
ENGINE_VERSION='0.8.0';SCHEMA_VERSION='8.0.0'
def canon(v:Any)->str:return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False)
def write(p:Path,v:dict[str,Any]):p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n',encoding='utf-8')
def main()->int:
 p=argparse.ArgumentParser();p.add_argument('--group8-root',type=Path,required=True);p.add_argument('--annual-registry',type=Path,required=True);p.add_argument('--lineage-amendment',type=Path,required=True);p.add_argument('--adapter-map',type=Path,required=True);p.add_argument('--categorical-dictionary',type=Path,required=True);p.add_argument('--value-bindings',type=Path,required=True);p.add_argument('--reference-resolution',type=Path,required=True);p.add_argument('--source-semantics',type=Path,required=True);p.add_argument('--design-audit',type=Path,required=True);a=p.parse_args();root=a.group8_root.resolve()
 annual=json.loads(a.annual_registry.read_text());lineage=json.loads(a.lineage_amendment.read_text());ad=json.loads(a.adapter_map.read_text());cats=json.loads(a.categorical_dictionary.read_text());bindings=json.loads(a.value_bindings.read_text());res=json.loads(a.reference_resolution.read_text());sem=json.loads(a.source_semantics.read_text());audit=json.loads(a.design_audit.read_text());gates={'annual_registry':annual.get('status')=='PASS','lineage_amendment':lineage.get('status')=='PASS_COHERENT_DEPENDENCY_LINEAGE','adapter_map':ad.get('status')=='PASS','categorical_dictionary':cats.get('status')=='PASS','value_bindings':bindings.get('status')=='PASS','reference_resolution':res.get('status')=='PASS','source_semantics':sem.get('status')=='PASS','design_contract_audit':audit.get('status')=='PASS'};bad=[k for k,v in gates.items() if not v]
 if bad:raise RuntimeError(f'freeze gates failed: {bad}')
 if annual.get('lineage_amendment_hash')!=lineage.get('amendment_hash'):raise RuntimeError('registry/amendment hash mismatch')
 if bindings.get('categorical_dictionary_hash')!=cats.get('dictionary_hash'):raise RuntimeError('binding/category mismatch')
 if bindings.get('source_semantics_evidence_hash')!=sem.get('evidence_hash'):raise RuntimeError('binding/source semantics mismatch')
 if res.get('binding_hash')!=bindings.get('binding_hash'):raise RuntimeError('resolution/binding mismatch')
 cfg=json.loads((root/'FROZEN_CONFIG_DRAFT.json').read_text());cfg.update({'config_status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'logical_dependency_lineage_id':annual['logical_lineage_id'],'coherent_lineage_amendment_hash':lineage['amendment_hash'],'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':sem['evidence_hash'],'design_reference_resolution_hash':res['resolution_hash'],'design_contract_audit_hash':audit['report_hash'],'resolved_definition_references':res['resolved_references'],'group7_logic_source':annual['group7_logic_source']});payload=copy.deepcopy(cfg);payload.pop('config_id',None);cfg['config_id']='cfg8_'+hashlib.sha256(canon(payload).encode()).hexdigest();write(root/'FROZEN_CONFIG.json',cfg)
 defs=json.loads((root/'01_DEFINITION_REGISTRY_CANDIDATE_v2.json').read_text());defs.update({'status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'config_id':cfg['config_id'],'logical_dependency_lineage_id':annual['logical_lineage_id'],'coherent_lineage_amendment_hash':lineage['amendment_hash'],'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':sem['evidence_hash'],'reference_resolution_hash':res['resolution_hash'],'design_contract_audit_hash':audit['report_hash']});defs['registry_hash']=hashlib.sha256(canon({k:v for k,v in defs.items() if k!='registry_hash'}).encode()).hexdigest();write(root/'01_DEFINITION_REGISTRY.json',defs)
 contract=json.loads((root/'contracts/UPSTREAM_INPUT_CONTRACT_DRAFT.json').read_text());contract.update({'contract_version':'1.0.0','status':'FROZEN','logical_dependency_lineage_id':annual['logical_lineage_id'],'coherent_lineage_amendment_hash':lineage['amendment_hash'],'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':sem['evidence_hash']});mapping={'group1_canonical_bars':'source','group2_regime':'group2','group3_structure':'group3','group4_zones':'group4','group5_liquidity':'group5','group6_imbalance_delivery':'group6','group7_blocks':'group7'}
 for key,item in contract.get('inputs',{}).items():
  group=mapping.get(key)
  if group:item['exact_table_adapter']={'adapter_map':'UPSTREAM_ADAPTER_MAP.json','group_key':group,'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary':'UPSTREAM_CATEGORICAL_DICTIONARY.json','categorical_dictionary_hash':cats['dictionary_hash'],'value_bindings':'UPSTREAM_VALUE_BINDINGS.json','value_binding_hash':bindings['binding_hash'],'lineage':annual['lineage'],'logical_lineage_id':annual['logical_lineage_id']}
 contract['contract_hash']=hashlib.sha256(canon({k:v for k,v in contract.items() if k!='contract_hash'}).encode()).hexdigest();write(root/'contracts/UPSTREAM_INPUT_CONTRACT.json',contract)
 schema=(root/'02_SCHEMA_CANDIDATE_v2.sql').read_text();(root/'02_SCHEMA.sql').write_text(schema);schema_hash=hashlib.sha256(schema.encode()).hexdigest()
 design=(root/'00_DESIGN_LOCK_DRAFT.md').read_text();design=design.replace('## Design Lock Draft v0.8.0-draft.1','## Design Lock v0.8.0');design=design.replace('**Status:** DRAFT ONLY — NOT FROZEN — ENGINE BUILD AND ANNUAL EXECUTION FORBIDDEN UNTIL DEPENDENCY INTAKE PASS','**Status:** FROZEN — COHERENT DEPENDENCY INTAKE PASS — ENGINE BUILD AUTHORIZED FOR 2023 ONLY; 2024 OOS FORBIDDEN UNTIL 2023 FREEZE')
 start=design.find('## 3. Dependency and freeze gate');end=design.find('## 4. Time and causality contract')
 if start<0 or end<=start:raise RuntimeError('dependency gate section not found')
 gate=f'''## 3. Dependency and freeze gate\n\n**FROZEN PASS.**\n\n1. Runtime bundle v3 is the exact corrected Groups2–6 source; all engine SHA-256 identities pass.\n2. Group7 logic is unchanged v0.7.5 from closure `{annual['group7_logic_source']['closure_tag']}` / `{annual['group7_logic_source']['closure_commit_sha']}`.\n3. Groups2–7 are rebuilt as one coherent lineage `{annual['logical_lineage_id']}` for 2023 and untouched 2024 OOS.\n4. Every annual database passes public release re-download, SHA-256, size, SQLite quick/integrity/foreign-key, exact-schema and categorical intake.\n5. Cross-year validation and lineage amendment hashes are `{annual['cross_year']['report_hash']}` and `{lineage['amendment_hash']}`.\n6. Exact adapter, categorical, source-semantics, value-binding and definition-reference gates pass with hashes `{ad['adapter_map_hash']}`, `{cats['dictionary_hash']}`, `{sem['evidence_hash']}`, `{bindings['binding_hash']}`, `{res['resolution_hash']}`.\n7. Definition Candidate v2 and Schema Candidate v2 are the only frozen ontology/persistence artifacts.\n8. No lossy upstream-ID bridge, historical clobbered data tag, guessed identifiers, mutable dependency access, BUY/SELL/entry/SL/TP/risk/PnL/future-return or preferred-school ranking is allowed.\n\n''';design=design[:start]+gate+design[end:]
 design+=f'''\n## Frozen artifact identities\n\n- Engine version: `{ENGINE_VERSION}`\n- Schema version: `{SCHEMA_VERSION}`\n- Config ID: `{cfg['config_id']}`\n- Definition registry hash: `{defs['registry_hash']}`\n- Upstream contract hash: `{contract['contract_hash']}`\n- SQL schema SHA-256: `{schema_hash}`\n- Coherent lineage amendment hash: `{lineage['amendment_hash']}`\n- Annual dependency registry hash: `{annual['registry_hash']}`\n- Adapter map hash: `{ad['adapter_map_hash']}`\n- Categorical dictionary hash: `{cats['dictionary_hash']}`\n- Value binding hash: `{bindings['binding_hash']}`\n- Source semantics evidence hash: `{sem['evidence_hash']}`\n- Reference resolution hash: `{res['resolution_hash']}`\n- Design contract audit hash: `{audit['report_hash']}`\n''';(root/'00_DESIGN_LOCK.md').write_text(design)
 status=json.loads((root/'STATUS.json').read_text());status.update({'annual_execution_authorized':True,'config_id':cfg['config_id'],'design_frozen':True,'engine_build_authorized':True,'officially_closed':False,'proposed_engine_version':ENGINE_VERSION,'proposed_schema_version':SCHEMA_VERSION,'status':'DESIGN_FROZEN_ENGINE_BUILD_AUTHORIZED_2023_ONLY','logical_dependency_lineage_id':annual['logical_lineage_id'],'coherent_lineage_amendment_hash':lineage['amendment_hash'],'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':sem['evidence_hash'],'reference_resolution_hash':res['resolution_hash'],'design_contract_audit_hash':audit['report_hash']});status['dependency_intake']={k:'PASS' for k in gates};write(root/'STATUS.json',status)
 manifest={'format_version':3,'status':'FROZEN','engine_version':ENGINE_VERSION,'schema_version':SCHEMA_VERSION,'config_id':cfg['config_id'],'logical_dependency_lineage_id':annual['logical_lineage_id'],'coherent_lineage_amendment_hash':lineage['amendment_hash'],'definition_registry_hash':defs['registry_hash'],'upstream_contract_hash':contract['contract_hash'],'schema_sha256':schema_hash,'annual_dependency_registry_hash':annual['registry_hash'],'adapter_map_hash':ad['adapter_map_hash'],'categorical_dictionary_hash':cats['dictionary_hash'],'value_binding_hash':bindings['binding_hash'],'source_semantics_evidence_hash':sem['evidence_hash'],'reference_resolution_hash':res['resolution_hash'],'design_contract_audit_hash':audit['report_hash'],'group7_logic_source':annual['group7_logic_source']};manifest['design_freeze_hash']=hashlib.sha256(canon(manifest).encode()).hexdigest();write(root/'DESIGN_FREEZE_MANIFEST.json',manifest);print(json.dumps(manifest,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
